In [13]:
import pandas as pd

In [14]:
df = pd.read_excel("/home/groups/NGSdev/projects/evansmds/mds_data/805_data_20250107.xlsx") 
df.head()

,MLL ID,Gender 1=female;2=male,Age,Final Diagnosis,Status EN,Clinical Status EN,sample date,Analyses,WBC,HB,...,STAG2,SUZ12,TET2,TP53,U2AF1,U2AF2,UBA1,WT1,ZEB2,ZRSR2
0,MLL_10694,2,27.0,MDS RA (nach WHO),Primary diagnosis,Primary diagnosis,2005-09-22,ZCFMI,1000.0,8.5,...,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE
1,MUC_00041,2,46.0,MDS RAEB-1 (nach WHO),Primary diagnosis,Primary diagnosis,2005-09-23,ZCFM,2900.0,7.4,...,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,POSITIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE
2,MLL_54186,1,82.0,MDS RAEB-2 (nach WHO),Primary diagnosis,Primary diagnosis,2005-10-13,ZCMI,NaN,NaN,...,NEGATIVE,NEGATIVE,POSITIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE
3,MLL_10702,2,65.7,MDS RA (nach WHO),Primary diagnosis,Primary diagnosis,2005-11-21,ZCFMI,3200.0,13.0,...,NEGATIVE,NEGATIVE,POSITIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE
4,MUC_00201,1,34.7,"MDS, 5q- Syndrom (nach WHO)",Primary diagnosis,Primary diagnosis,2006-01-06,ZCFMI,3320.0,9.4,...,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE

In [15]:
df = df.assign(gender = lambda x: x['Gender 1=female;2=male'] - 1)

df = df.assign(age = lambda x: x['Age'] / 100)
df.head()

,MLL ID,Gender 1=female;2=male,Age,Final Diagnosis,Status EN,Clinical Status EN,sample date,Analyses,WBC,HB,...,TET2,TP53,U2AF1,U2AF2,UBA1,WT1,ZEB2,ZRSR2,gender,age
0,MLL_10694,2,27.0,MDS RA (nach WHO),Primary diagnosis,Primary diagnosis,2005-09-22,ZCFMI,1000.0,8.5,...,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE,1,0.270
1,MUC_00041,2,46.0,MDS RAEB-1 (nach WHO),Primary diagnosis,Primary diagnosis,2005-09-23,ZCFM,2900.0,7.4,...,NEGATIVE,NEGATIVE,POSITIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE,1,0.460
2,MLL_54186,1,82.0,MDS RAEB-2 (nach WHO),Primary diagnosis,Primary diagnosis,2005-10-13,ZCMI,NaN,NaN,...,POSITIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE,0,0.820
3,MLL_10702,2,65.7,MDS RA (nach WHO),Primary diagnosis,Primary diagnosis,2005-11-21,ZCFMI,3200.0,13.0,...,POSITIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE,1,0.657
4,MUC_00201,1,34.7,"MDS, 5q- Syndrom (nach WHO)",Primary diagnosis,Primary diagnosis,2006-01-06,ZCFMI,3320.0,9.4,...,NEGATIVE,NEGATIVE,NEGATIVE,NEGATIVE,NaN,NEGATIVE,NaN,NEGATIVE,0,0.347

In [17]:
df.columns.tolist()

['MLL ID',
 'Gender 1=female;2=male',
 'Age',
 'Final Diagnosis',
 'Status EN',
 'Clinical Status EN',
 'sample date',
 'Analyses',
 'WBC',
 'HB',
 'Platelets',
 'other material 1',
 'other material 2',
 'Heparin Staining in Z',
 'Mat in Z EN',
 'Z Diagnosis',
 'Z Report',
 '% Blasts in PB',
 '% Blasts im BM',
 '% Neutrophils in PB',
 'C Diagnosis',
 'C Report',
 'Karyotype 1',
 'K1 Cells',
 'Karyotype 2',
 'K2 Cells',
 'Karyotype 3',
 'K3 Cells',
 'Karyotype 4',
 'K4 Cells',
 'Karyotype 5',
 'K5 Cells',
 'Karyotype 6',
 'K6 Cells',
 'FISH Diagnosis',
 'FISH Report',
 'FISH ISCN Formula 1',
 'FISH ISCN Formula 2',
 'FISH ISCN Formula 3',
 'FISH ISCN Formula 4',
 'M Diagnosis',
 'M Report',
 'M Report EN',
 'I Diagnosis',
 'I Report',
 'I Report EN',
 'Clinical Diagnosis',
 'Date of Diagnosis',
 'Overall survival (days)',
 'Prognostic Score Name',
 'Prognostic Score Value',
 'Date Last FU',
 'Date of Death',
 'Cause of Death',
 'Cause of Death EN',
 'Familial Disease',
 'Histology',
 'Histology EN',
 'Date of Relapse',
 'Date of Remission',
 'ASXL1',
 'ASXL2',
 'ATRX',
 'BCOR',
 'BCORL1',
 'BRAF',
 'CALR',
 'CBL',
 'CEBPA',
 'CSF3R',
 'CSNK1A1',
 'CUX1',
 'DDX41',
 'DNMT3A',
 'ETNK1',
 'ETV6',
 'EZH2',
 'FBXW7',
 'FLT3',
 'GATA1',
 'GATA2',
 'GNB1',
 'IDH1',
 'IDH2',
 'IL6R',
 'JAK2',
 'KIT',
 'KRAS',
 'MPL',
 'MYD88',
 'NF1',
 'NOTCH1',
 'NPM1',
 'NRAS',
 'PDGFRA',
 'PDGFRB',
 'PHF6',
 'PIGA',
 'PPM1D',
 'PRPF8',
 'PTEN',
 'PTPN11',
 'RAD21',
 'RUNX1',
 'SETBP1',
 'SF1',
 'SF3A1',
 'SF3B1',
 'SH2B3',
 'SMC1A',
 'SMC3',
 'SRSF2',
 'STAG2',
 'SUZ12',
 'TET2',
 'TP53',
 'U2AF1',
 'U2AF2',
 'UBA1',
 'WT1',
 'ZEB2',
 'ZRSR2',
 'gender',
 'age']

In [22]:
df['Prognostic Score Value'].value_counts()

Prognostic Score Value
Low (2-3)           240
Intermediate (3)    144
Very Low (0-1)       93
High (5-6)           73
Very High (>6)       65
Name: count, dtype: int64

In [20]:
df[['HB']]

       HB
0     8.5
1     7.4
2     NaN
3    13.0
4     9.4
..    ...
669  10.4
670  10.7
671   NaN
672   8.7
673  10.0

[674 rows x 1 columns]